### ISSUE TITLE
默认 Credentials 文件位置错误

### ISSUE THREAD

**Issue by xiao201208** [aliyun/credentials-python#31]
按照说明，默认的 Credentials 文件 应该是在用户目录的 `~/.alibabacloud/credentials.ini` 文件，而实际却是根目录下。

![image](https://user-images.githubusercontent.com/18691139/202150169-ff61966c-82e1-481d-ad7f-428d63748b4c.png)

`file_path = os.path.join(ac.HOME, "/.alibabacloud/credentials.ini") ` 应该改为 `file_path = os.path.join(ac.HOME, ".alibabacloud/credentials.ini")`

**Comment by yndu13** [comment]
已修复，修复pr：https://github.com/aliyun/credentials-python/pull/33
